version: "1.0"
services:
  php:
    build:
      context: .
    container_name: zf2.5
    volumes:
      - .:/www

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf

